feat: support pnpm lockfile version 6.0 which is generated by pnpm 8
aspect-build/rules_js pull request #973
Opened 2023-03-29 23:47 UTC by gregmagolan

2023-03-29 23:51 UTC, kormide approved these changes

2023-03-30 00:02 UTC, jbedard requested changes
I think we need new tests? Can we create a test for each lockfile version we support?

Probably create a v5 one as the base, then upgrade to v6 and check that in as a new test and leave the v5 as is etc...

2023-03-30 00:05 UTC, gregmagolan commented
Yes, planning to add better test coverage before this lands.

2023-03-31 01:56 UTC, gregmagolan commented
Added unit test for v5 and v6 formats and updated a subset of e2e tests to v6. I'm happy with that coverage.

2023-03-31 02:18 UTC, kormide approved these changes

2023-03-31 04:07 UTC, merged